

# This file was *autogenerated* from the file cosz_eq_i.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_5 = Integer(5); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1)
for k in range(_sage_const_0 ,_sage_const_5 ):
    print(f'Para k = {k}')
    a = _sage_const_2 /( sinh( (_sage_const_2 *k+_sage_const_1 )*pi ) * cos( (-_sage_const_1 )**(k+_sage_const_1 )*log(_sage_const_1 +sqrt(_sage_const_2 )) ) + I*cosh( (_sage_const_2 *k+_sage_const_1 )*pi )*sin( (-_sage_const_1 )**(k + _sage_const_1 )*log(sqrt(_sage_const_2 ) + _sage_const_1 ) ) )
    b = _sage_const_2 /( sinh( (_sage_const_2 *k+_sage_const_1 )*pi )*cos( _sage_const_2 *(-_sage_const_1 )**(k+_sage_const_1 )*log(_sage_const_1 +sqrt(_sage_const_2 )) ) + I*cosh( (_sage_const_2 *k+_sage_const_1 )*pi )*sin( _sage_const_2 *(-_sage_const_1 )**(k+_sage_const_1 )*log(_sage_const_1 +sqrt(_sage_const_2 )) ) )
    c = _sage_const_2 /( sinh( (_sage_const_2 *k+_sage_const_1 )*pi )*sin( _sage_const_2 *(-_sage_const_1 )**(k+_sage_const_1 )*log(_sage_const_1 +sqrt(_sage_const_2 )) ) + I*cosh( (_sage_const_2 *k+_sage_const_1 )*pi )*cos( _sage_const_2 *(-_sage_const_1 )**(k+_sage_const_1 )*log(_sage_const_1 +sqrt(_sage_const_2 )) ) )
    d = _sage_const_2 /(sinh((_sage_const_2 *k+_sage_const_1 )*pi)*sin((-_sage_const_1 )**(k+_sage_const_1 )*log(_sage_const_1 +sqrt(_sage_const_2 ))) + I*cosh((_sage_const_2 *k+_sage_const_1 )*pi)*cos((-_sage_const_1 )**(k+_sage_const_1 )*log(_sage_const_1 +sqrt(_sage_const_2 ))))

    print(f'a = {N(a)}')
    print(f'b = {N(b)}')
    print(f'c = {N(c)}')
    print(f'd = {N(d)}')

    __tmp__=var("arg"); sol = symbolic_expression(_sage_const_1 /_sage_const_2 *cos(_sage_const_1 /_sage_const_2 *arcsinh(_sage_const_2 /arg)) ).function(arg)#2*pi*k + arccos(-i)

    print(N(sol(a)))
    print(N(sol(b)))
    print(N(sol(c)))
    print(N(sol(d)))

    #print(f'coth-tanh = {N(coth(sol)-tanh(sol))} \n')

    
print(f'{N(coth(arccos(-i))-tanh(arccos(-i)))}')

