

# This file was *autogenerated* from the file eto-zto2+1-.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_20 = Integer(20); _sage_const_6p2832 = RealNumber('6.2832'); _sage_const_0p21460 = RealNumber('0.21460'); _sage_const_0p78540 = RealNumber('0.78540')
for n in range(_sage_const_0 ,_sage_const_20 ):
    z1=-sqrt(_sage_const_6p2832  * i * n - (_sage_const_0p21460  + _sage_const_0p78540  * I) )
    z2= sqrt(_sage_const_6p2832  * i * n - (_sage_const_0p21460  + _sage_const_0p78540  * I) )

    print(f'z1 = {z1}, \t \t z2 = {z2}')

