

# This file was *autogenerated* from the file integral_def.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_25 = Integer(25); _sage_const_4 = Integer(4); _sage_const_1 = Integer(1)
f = (x*sin(x))/((x**_sage_const_2 -_sage_const_25 )*(_sage_const_4 *x**_sage_const_2 +_sage_const_1 ))
f.integral(x,-oo,oo)

