

# This file was *autogenerated* from the file integral.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_4 = Integer(4); _sage_const_0 = Integer(0); _sage_const_1 = Integer(1)
x,y = var('x,y', domain = 'real')
# Define the function
z = x+I*y
f = (z**_sage_const_2 +_sage_const_4 )/sin(pi*z)

# Define the contour
C = circle((_sage_const_0 ,_sage_const_0 ), _sage_const_1 )

# Compute the integral
integral(f, C)

