

# This file was *autogenerated* from the file transf_fourier.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1)
from sage.all import *

x, x_0, w = var('x x_0 w', domain = 'real')
assume(w>_sage_const_0 )
hbar, N = var('hbar N', domain = 'real')
assume(hbar>_sage_const_0 )

psi_x = N*exp(-x**_sage_const_2 /_sage_const_2 )

transformada = _sage_const_1 /sqrt(_sage_const_2 *pi)*integral(psi_x*exp(-I*w*x),(x,-oo,oo))
print(latex(transformada))

