

# This file was *autogenerated* from the file transf_fourier.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1)
from sage.all import *

y, p, N, xbar, x = var('y p N xbar x', domain = 'real')
hbar = var('hbar', domain = 'real', latex_name = '\\hbar')
assume(hbar>_sage_const_0 )
assume(xbar>_sage_const_0 )

psi_x = N*hermite(_sage_const_2 ,y)*exp(-y**_sage_const_2 /_sage_const_2 )
#psi_x = exp(-1/2*x^2/xbar^2)
print(f'psi_x: {psi_x}')

transformada = _sage_const_1 /sqrt(_sage_const_2 *pi*hbar)*integral(psi_x*exp(-I*p*y/hbar),(y,-oo,oo))
#transformada = integral(psi_x*cos(p*x/hbar),(x,-oo,oo))
print(latex(transformada.simplify_full()))

#for i in range(10):
#    print(hermite(i,x))

