

# This file was *autogenerated* from the file cono_geodesica.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_0 = Integer(0)# Definir las variables y la función
var('t a')
r, v = function('r')(t), function('v')(t)

# Definir el sistema de ecuaciones diferenciales
sistema_ecuaciones = [
    diff(r, t) == v,
    diff(v, t) == a * abs(v) / abs(r)**_sage_const_2 
]

# Condiciones iniciales (cámbialas según tus necesidades)
condiciones_iniciales = [r(_sage_const_0 ) == r0, v(_sage_const_0 ) == v0]

# Resolver el sistema de ecuaciones diferenciales
solucion = desolve_system(
    sistema_ecuaciones,
    [r, v],
    ics=condiciones_iniciales,
    algorithm='rk4'
)

# Mostrar la solución
show(solucion)


